SymfonyDoTaskBundle_task:
  resource: "@SymfonyDoTaskBundle/Resources/config/routing/task.yml"
  prefix:   /task

SymfonyDoTaskBundle_index:
  path: /
  defaults: { _controller: SymfonyDoTaskBundle:Task:index }
