parameters:
#    symfony_do_task.example.class: SymfonyDo\TaskBundle\Example

services:
#    symfony_do_task.example:
#        class: %symfony_do_task.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
